### ISSUE TITLE
Rebrew | Advanced Rebrew

### ISSUE THREAD

**Issue by paul-lapczynski** [plapczyn/webrew#15]
*Description*
- Add fields to Rebrew for a more robust, detailed, and complete Rebrew. 

*Confirmation*
- I am able to complete a rebrew in a way that the results can be analyzed and displayed in a graph

**Comment by petelapczynski** [comment]
added advanced calculation averages to methods/rebrew.js

**Comment by petelapczynski** [comment]
really charts.js..... really..... responsive: true...
